// <auto-generated />
using System;
using MasterDance.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterDance.Web.Data.Migrations
{
    [DbContext(typeof(MasterDanceContext))]
    [Migration("20181118195932_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ExpirationDate");

                    b.Property<int>("MemberId");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TypeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MemberId");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(128);

                    b.Property<string>("MemberType")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator<string>("MemberType").HasValue("Person");
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Member", b =>
                {
                    b.HasBaseType("MasterDance.Web.Data.Entities.Person");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<int?>("FatherId");

                    b.Property<string>("Image");

                    b.Property<DateTime?>("JoinedDate");

                    b.Property<int?>("MotherId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Member");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Document", b =>
                {
                    b.HasOne("MasterDance.Web.Data.Entities.Member", "Member")
                        .WithMany("Documents")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MasterDance.Web.Data.Entities.DocumentType", "Type")
                        .WithMany("Documents")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MasterDance.Web.Data.Entities.Blob", "Content", b1 =>
                        {
                            b1.Property<int>("DocumentId");

                            b1.Property<string>("Content")
                                .IsRequired();

                            b1.Property<string>("ContentType")
                                .HasMaxLength(32);

                            b1.Property<string>("FileName")
                                .HasMaxLength(255);

                            b1.ToTable("Documents");

                            b1.HasOne("MasterDance.Web.Data.Entities.Document")
                                .WithOne("Content")
                                .HasForeignKey("MasterDance.Web.Data.Entities.Blob", "DocumentId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Image", b =>
                {
                    b.HasOne("MasterDance.Web.Data.Entities.Member", "Member")
                        .WithMany("Images")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Person", b =>
                {
                    b.OwnsOne("MasterDance.Web.Data.Entities.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("PersonId");

                            b1.Property<string>("Address")
                                .HasMaxLength(255);

                            b1.Property<string>("Email")
                                .HasMaxLength(255);

                            b1.Property<string>("Phone")
                                .HasMaxLength(255);

                            b1.ToTable("Persons");

                            b1.HasOne("MasterDance.Web.Data.Entities.Person")
                                .WithOne("Contact")
                                .HasForeignKey("MasterDance.Web.Data.Entities.Contact", "PersonId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("MasterDance.Web.Data.Entities.Member", b =>
                {
                    b.HasOne("MasterDance.Web.Data.Entities.Person", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId");

                    b.HasOne("MasterDance.Web.Data.Entities.Person", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId");
                });
#pragma warning restore 612, 618
        }
    }
}
