POST https://localhost:5001/api/Memberships/CalculateMemberships
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjM2Y2MxNzkxN2YxY2M2NmEyNTFlNzNlNzhmOTA1ZTllIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDkzMDU0MTIsImV4cCI6MTU0OTMwOTAxMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJ3ZWJhcGkiXSwiY2xpZW50X2lkIjoid2ViYXBwIiwic3ViIjoiMSIsImF1dGhfdGltZSI6MTU0OTMwNTQxMiwiaWRwIjoibG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwic2NvcGUiOlsid2ViYXBpIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbImN1c3RvbSJdfQ.YIL21Jl_JBtc87Trrvx4ukg4pphbf6N3Z-jc3QJZ2baujH2HqDhjyZmv6b-9JGhd5sepcFzNQ5TH1w25hgJeC9n6FvQ0L65qyvMUK4ifl8H_XKnzCRxrHEtReyDlxcpC8Zu2CZK2oI-tXwPNoS0ahwVFhVuzhKrjVlIpsbrq8rYaVUCkHTCFLBzwjpMxGVvXPZfoIOK60EiSvRvqs3Tr9huncDUDJe2e5OpQMkz7OIIhZqimLDkz6rC8Wmd8PVy7ajQd8vbGeDfBRUCvx4lZf2r6IcNuec6E7sqNIEazcBMhABc6MZcEZlhM5dqXrADC14VRRROkZNbYNmsV3neccw

{"year": 2019, "month": 1}
###

GET https://localhost:5001/api/Memberships/GetDebtList
###